### ISSUE TITLE
slp axshistoryminutely usd

### ISSUE THREAD

**Issue by felixsim** [iKairos/axie-slp-discord-bot-notifier#1]
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'assets/images/graphs/axs/minutely.png'

**Comment by iKairos** [comment]
Hi! Since we gitignored the assets directory folder, you need to create the said directory manually. Notify us if any problems persist! Thank you so much!

EDIT: We've created a preparer for anyone who is running the repo for the first time! You can pull the repo and run `preparer.py` to create all the files and directories necessary for the bot to function. This might solve the issue! If anything unusual happens you can open another issue and the devs will take care of it! Thank you!
